import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform } from "react-native";
import { GeneratedStory } from "@/shared/types";

/**
 * Generates a formatted PDF for a bedtime story and opens the native share sheet.
 * Uses expo-print to render an HTML template to PDF, then expo-sharing to share.
 */
export async function shareStoryAsPdf(story: GeneratedStory): Promise<void> {
  const html = buildStoryHtml(story);

  if (Platform.OS === "web") {
    // On web, open a print dialog instead
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.print();
    }
    return;
  }

  // Generate PDF file
  const { uri } = await Print.printToFileAsync({ html, base64: false });

  // Share the PDF
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: `Share "${story.title}"`,
      UTI: "com.adobe.pdf",
    });
  }
}

function buildStoryHtml(story: GeneratedStory): string {
  const { title, paragraphs, config } = story;

  const characterLabel = config.characterType === "Custom" && config.customCharacter
    ? config.customCharacter
    : config.characterType;

  const metaLine = [
    characterLabel,
    config.scenario,
    config.style,
    config.language ?? "English",
    config.lengthMinutes ? `~${config.lengthMinutes} min` : null,
  ].filter(Boolean).join("  ·  ");

  const childName = config.childName && config.childName !== "the little one"
    ? config.childName
    : null;

  const paragraphsHtml = paragraphs
    .map((p) => `<p class="paragraph">${escapeHtml(p)}</p>`)
    .join("\n");

  const dedicationHtml = childName
    ? `<p class="dedication">A bedtime story for <em>${escapeHtml(childName)}</em> 🌙</p>`
    : `<p class="dedication">A magical bedtime story 🌙</p>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;1,400&family=Nunito:wght@400;700;800&display=swap');

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Lora', Georgia, serif;
      background: #FFFDF7;
      color: #2C1A4E;
      padding: 48px 56px;
      max-width: 680px;
      margin: 0 auto;
      line-height: 1.8;
    }

    .header {
      text-align: center;
      margin-bottom: 36px;
      padding-bottom: 28px;
      border-bottom: 2px solid #E8D9F5;
    }

    .moon {
      font-size: 48px;
      display: block;
      margin-bottom: 12px;
    }

    .app-name {
      font-family: 'Nunito', sans-serif;
      font-size: 13px;
      font-weight: 700;
      letter-spacing: 2px;
      text-transform: uppercase;
      color: #9B7DC8;
      margin-bottom: 20px;
    }

    h1 {
      font-family: 'Nunito', sans-serif;
      font-size: 28px;
      font-weight: 800;
      color: #2C1A4E;
      line-height: 1.3;
      margin-bottom: 10px;
    }

    .meta {
      font-family: 'Nunito', sans-serif;
      font-size: 12px;
      color: #9B7DC8;
      letter-spacing: 0.5px;
    }

    .dedication {
      font-style: italic;
      font-size: 15px;
      color: #7A5BA8;
      text-align: center;
      margin: 28px 0 36px;
    }

    .paragraph {
      font-size: 16px;
      line-height: 1.9;
      margin-bottom: 22px;
      text-indent: 1.5em;
      color: #2C1A4E;
    }

    .paragraph:first-of-type {
      text-indent: 0;
    }

    .paragraph:first-of-type::first-letter {
      font-family: 'Nunito', sans-serif;
      font-size: 52px;
      font-weight: 800;
      float: left;
      line-height: 0.85;
      margin-right: 6px;
      margin-top: 4px;
      color: #7A5BA8;
    }

    .footer {
      margin-top: 48px;
      padding-top: 20px;
      border-top: 2px solid #E8D9F5;
      text-align: center;
    }

    .footer-stars {
      font-size: 18px;
      letter-spacing: 6px;
      display: block;
      margin-bottom: 8px;
    }

    .footer-text {
      font-family: 'Nunito', sans-serif;
      font-size: 12px;
      color: #C8B8E8;
      letter-spacing: 1px;
    }
  </style>
</head>
<body>
  <div class="header">
    <span class="moon">🌙</span>
    <div class="app-name">Dreamy Tales</div>
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">${escapeHtml(metaLine)}</div>
  </div>

  ${dedicationHtml}

  <div class="story-body">
    ${paragraphsHtml}
  </div>

  <div class="footer">
    <span class="footer-stars">✨ ⭐ ✨</span>
    <div class="footer-text">THE END &nbsp;·&nbsp; Generated by Dreamy Tales</div>
  </div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
